import Head from "next/head";
import React from "react";
import Author from "../components/Author";
import Banner from "../components/Banner";
import CtaReady from "../components/CtaReady";
import DidKnow from "../components/DidKnow";
import Ebook from "../components/Ebook";
import Inside from "../components/Inside";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Convin</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Banner />
			<Ebook />
			<Inside />
			<CtaReady />
			<DidKnow />
			<Author />
		</div>
	);
}
